---
- name: Converge
  hosts: all
  become: true

  vars:
    influxdb_container_user: root
    influxdb_username: "admin"
    influxdb_password: "&*!!p4zz!"
    influxdb_org: "home"
    influxdb_bucket: "bucket"
    influxdb_token: "ffe8006b-9bc0-4421-aa09-942ad8ebcb9a"

  roles:
    - role: iasensio.influxdb
